from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Checkout(object):
    def setupUi(self, Checkout):
        Checkout.setObjectName("Checkout")
        Checkout.resize(749, 579)
        self.centralwidget = QtWidgets.QWidget(Checkout)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 141, 41))
        self.label.setObjectName("label")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(30, 460, 121, 24))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.TotalLabel = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TotalLabel.setFont(font)
        self.TotalLabel.setObjectName("TotalLabel")
        self.total = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total.setFont(font)
        self.total.setObjectName("total")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(460, 450, 261, 41))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.checkout = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkout.setFont(font)
        self.checkout.setObjectName("checkout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 80, 671, 341))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        Checkout.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Checkout)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 749, 26))
        self.menubar.setObjectName("menubar")
        Checkout.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Checkout)
        self.statusbar.setObjectName("statusbar")
        Checkout.setStatusBar(self.statusbar)

        self.retranslateUi(Checkout)
        QtCore.QMetaObject.connectSlotsByName(Checkout)

    def retranslateUi(self, Checkout):
        _translate = QtCore.QCoreApplication.translate
        Checkout.setWindowTitle(_translate("Checkout", "Checkout"))
        self.label.setText(_translate("Checkout", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ff0000;\">Your Cart</span></p></body></html>"))
        self.TotalLabel.setText(_translate("Checkout", "Total :"))
        self.total.setText(_translate("Checkout", "0"))
        self.checkout.setText(_translate("Checkout", "Checkout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Checkout = QtWidgets.QMainWindow()
    ui = Ui_Checkout()
    ui.setupUi(Checkout)
    Checkout.show()
    sys.exit(app.exec_())

